# Setup
title:            Amedeo Ceruti
tagline:          'Chemical Engineer with some CS'
description:      'Personal webpage of Amedeo Ceruti. Chemical Engineer from Barcelona, Spain, currently in Germany. Reach me at <a href="https://twitter.com/amedeoceruti" target="_blank">@AmedeoCeruti</a>.'
url:              https://ddceruti.github.io/
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
